version: '3'
services:
  web:
    build: .
    ports:
      - 5002:5002
    volumes:
      - ./run.py:/app/run.py
      - ./requirements.txt:/app/requirements.txt
      - ./sabir/site.sqlite3:/app/sabir/app/database/app.sqlite3
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
  db:
    image: sqlite:latest
    volumes:
      - ./sabir/app.sqlite3:/app/sabir/app.sqlite3

volumes:
  db-data: